-- The catalog itself: 26 references, their sizes and their stock.
-- Product copy is French because it is shop content, not code.

insert into products (sku, name, summary, detail, price_cents, stock, category, is_new, material) values
  ('COQ-AFFICHE-TYPO', 'Affiche « Rien d''autre »', 'A2, composition typographique, encre olive.', 'Le slogan composé au plomb puis imprimé en typographie, une seule encre. Le foulage se sent sous le doigt : c''est ce qui distingue une impression d''une photocopie.', 2200, 40, 'Affiches', 0, 'Papier chiffon 250 g, typographie'),
  ('COQ-BONNET', 'Bonnet « Kernel panic »', 'Maille double, panique contenue.', 'Maille côtelée double épaisseur, rouge signal — la couleur exacte de l''écran qu''on préférerait ne pas voir. À enfiler quand tout s''effondre : la panique s''arrête aux oreilles, le reste du système repart au chaud. Compatible embruns, gel et post-mortems en terrasse.', 2400, 42, 'Vêtements', 1, 'Laine côtelée double, rouge signal'),
  ('COQ-BOUGIE', 'Bougie « Marée basse »', 'Cire de colza, 40 heures, iode et pin.', 'Iode, pin maritime et un fond de bois flotté. Cire de colza coulée à Quimper, mèche coton, quarante heures de brûlage dans un verre qu''on garde après.', 2200, 60, 'Maison', 1, 'Cire de colza, mèche coton, 220 g'),
  ('COQ-CARNET', 'Carnet de post-mortem', 'A5, papier pointillé, couverture rigide.', 'Cent quarante pages pointillées pour vos post-mortems, avec en première page la liste des questions à se poser avant d''accuser le réseau.', 1600, 37, 'Papeterie', 0, 'Papier pointillé 100 g, couverture rigide'),
  ('COQ-CARTE-MARINE', 'Carte marine de la rade', 'A2, la rade de Brest au 1/50 000.', 'La rade relevée au 1/50 000, sondes comprises, imprimée en deux tons sur papier mat. Assez juste pour naviguer, assez belle pour rester au mur.', 2900, 25, 'Affiches', 1, 'Papier mat 200 g, deux tons'),
  ('COQ-CARTES', 'Cartes postales, lot de huit', 'Huit dessins, papier 300 g, dos écrit.', 'Huit cartes du bord de mer brestois, imprimées en offset sur un 300 g qui accepte le stylo plume. Le dos porte une phrase différente sur chacune ; on vous laisse la découvrir.', 1200, 90, 'Papeterie', 0, 'Papier 300 g, impression offset'),
  ('COQ-CASQUETTE', 'Casquette « 4 ms »', 'Six panneaux, visière courbe, taille unique.', 'Coton lavé six panneaux, fermeture métal réglable, broderie du chiffre qui nous tient lieu de fierté. Taille unique, tour de tête 54 à 61 cm.', 2400, 52, 'Vêtements', 1, 'Coton lavé, broderie fil olive'),
  ('COQ-CHAUSSETTES', 'Chaussettes unikernel', 'Une paire, motif pinces, taille unique.', 'Motif pinces discret, fil d''Écosse. Portées par toute l''équipe le jour du déploiement, ce qui explique peut-être le taux de disponibilité.', 1400, 88, 'Vêtements', 0, 'Fil d''Écosse, taille unique'),
  ('COQ-CLEF', 'Clé USB image d''or', 'Une image Bernard de démonstration, gravée.', 'Trois mégaoctets d''image de démonstration sur une clé qui en fait mille fois plus. Le contraste est le message.', 3400, 8, 'Accessoires', 0, 'Aluminium gravé, 32 Go'),
  ('COQ-CRAYONS', 'Crayons gravés, lot de trois', 'HB, 2B, 4B, bois non verni.', 'Trois duretés, en bois de cèdre non verni pour qu''on les taille avec plaisir. Gravés à chaud, sans peinture : ce qui n''est pas nécessaire n''est pas ajouté.', 900, 150, 'Papeterie', 0, 'Cèdre non verni, gravure à chaud'),
  ('COQ-ECHARPE', 'Écharpe côtelée', 'Laine mérinos, 180 cm, deux tours.', 'Mérinos filé au Portugal, côtes larges, assez longue pour deux tours sans étrangler. La couleur vient d''un bain unique : deux écharpes ne sont jamais tout à fait identiques.', 4900, 22, 'Vêtements', 0, 'Laine mérinos, 180 × 25 cm'),
  ('COQ-GILET', 'Gilet de quart', 'Sans manches, sans reproche.', 'Laine bouillie assez dense pour couper le vent du ponton, boutons en corozo cousus main. Le gilet des quarts de nuit : il laisse les bras libres pour taper au clavier et remonter les lignes — de pêche ou de code.', 7900, 0, 'Vêtements', 1, 'Laine bouillie, boutons corozo'),
  ('COQ-GOURDE', 'Gourde double paroi', 'Inox 500 ml, garde le chaud six heures.', 'Acier inoxydable à double paroi, bouchon à joint silicone, gravure au laser plutôt qu''impression — elle ne s''effacera pas au fond d''un sac. Six heures pour le chaud, douze pour le froid.', 2900, 45, 'Accessoires', 0, 'Acier inoxydable brossé, 500 ml'),
  ('COQ-HOODIE', 'Sweat à capuche Coquille', 'Molleton lourd, crabe brodé dans le dos.', 'Molleton 380 g gratté à l''intérieur, crabe brodé (pas imprimé) entre les omoplates. Taille grand, comme il se doit.', 6900, 17, 'Vêtements', 0, 'Molleton 380 g gratté, broderie fil olive'),
  ('COQ-MANCHES', 'T-shirt manches longues', 'Le même coton, les bras en plus.', 'La coupe du t-shirt court, allongée aux poignets, dans le même coton biologique 180 g. Bords-côtes aux manches pour qu''ils ne tirebouchonnent pas au troisième lavage.', 3900, 31, 'Vêtements', 1, 'Coton biologique 180 g, bords-côtes'),
  ('COQ-MARQUEPAGE', 'Marque-page en laiton', 'Une lame fine qui ne marque pas le papier.', 'Découpé dans une feuille de laiton de trois dixièmes, poli sur les bords. Il patine avec le temps, ce qui est le but.', 800, 0, 'Papeterie', 0, 'Laiton poli, 0,3 mm'),
  ('COQ-MUG', 'Mug 4 ms', 'Céramique, 350 ml, passe au lave-vaisselle.', 'Sur une face, « démarré en 4 ms » ; sur l''autre, la trace de boot complète en petits caractères. Le café, lui, reste lent.', 1900, 54, 'Accessoires', 0, 'Céramique émaillée, 350 ml'),
  ('COQ-PLAID', 'Plaid molleton', 'Grand format, molleton recyclé, franges nouées.', 'Cent quarante sur deux cents, en molleton recyclé assez lourd pour tenir sur les épaules sans glisser. Franges nouées une à une, ce qui explique le délai.', 7900, 14, 'Maison', 0, 'Molleton recyclé 400 g, 140 × 200 cm'),
  ('COQ-PORTECLES', 'Porte-clés crabe', 'Laiton émaillé, deux couleurs.', 'Un crabe de deux centimètres en laiton, émaillé à la main en deux passes. Assez lourd pour qu''on le sente dans la poche, assez petit pour qu''on l''oublie.', 1200, 200, 'Accessoires', 0, 'Laiton émaillé, anneau acier'),
  ('COQ-POSTER', 'Affiche du benchmark', 'A2, les deux colonnes, celle qui fâche comprise.', 'La planche des mesures du 16 août, imprimée en A2 sur papier mat 200 g — colonne séquentielle et colonne concurrente, sans rien cacher.', 2400, 35, 'Affiches', 1, 'Papier mat 200 g, format A2'),
  ('COQ-REBOOTS', 'Reboots', 'Bottes de pluie, remise à zéro instantanée.', 'Cuir gras hydrofuge, semelle crantée, couture Goodyear. En cas de plantage — averse, embruns, flaque plus profonde qu''annoncé — un redémarrage à sec suffit : les Reboots repartent toujours, sans rien perdre de leur état. Temps de démarrage : celui de les lacer.', 8900, 31, 'Vêtements', 1, 'Cuir gras, semelle crantée'),
  ('COQ-SOCKET', 'Socket d''hiver', 'Grosse laine, se lie au premier froid.', 'Grosse maille mérinos tricotée en petite série, talon renforcé. S''ouvre en novembre, écoute sur toutes les interfaces du canapé et garde la connexion jusqu''en mars : keep-alive garanti, aucun paquet perdu.', 1600, 54, 'Vêtements', 1, 'Laine mérinos, talon renforcé'),
  ('COQ-STICKERS', 'Planche d''autocollants', 'Douze autocollants découpés, vinyle mat.', 'Douze pièces : le crabe, le logo, les quatre millisecondes de boot, et huit blagues internes que vous comprendrez au bout d''un mois.', 900, 247, 'Accessoires', 0, 'Vinyle mat découpé, douze pièces'),
  ('COQ-THEIERE', 'Théière émaillée', 'Un litre, fonte émaillée, filtre inox.', 'Fonte émaillée à l''intérieur pour que le thé ne prenne pas le goût du métal, filtre inox amovible, un litre — de quoi tenir une revue de code entière.', 4900, 18, 'Maison', 0, 'Fonte émaillée, filtre inox'),
  ('COQ-TOTE', 'Tote bag de marché', 'Toile épaisse, anses renforcées, fond plat.', 'Une toile de coton 340 g qui tient debout toute seule une fois pleine. Fond plat, anses doublées, sérigraphie discrète en bas à droite. Passe en machine et n''en garde rien.', 1900, 120, 'Accessoires', 1, 'Toile de coton 340 g, anses doublées'),
  ('COQ-TSHIRT', 'T-shirt « Rien d''autre »', 'Coton bio, sérigraphie du slogan sur la poitrine.', 'Le slogan de la maison, imprimé petit sur le cœur : votre application, un noyau, rien d''autre. Coton biologique 180 g, coupe droite, encre à l''eau.', 2900, 34, 'Vêtements', 1, 'Coton biologique 180 g, encre à l''eau');

insert into variants (sku, size, stock, rank) values
  ('COQ-AFFICHE-TYPO', '', 40, 0),
  ('COQ-BONNET', '', 42, 1),
  ('COQ-BOUGIE', '', 60, 0),
  ('COQ-CARNET', '', 37, 0),
  ('COQ-CARTE-MARINE', '', 25, 0),
  ('COQ-CARTES', '', 90, 0),
  ('COQ-CASQUETTE', '', 52, 0),
  ('COQ-CHAUSSETTES', '36-39', 40, 1),
  ('COQ-CHAUSSETTES', '40-43', 33, 2),
  ('COQ-CHAUSSETTES', '44-46', 15, 3),
  ('COQ-CLEF', '', 8, 0),
  ('COQ-CRAYONS', '', 150, 0),
  ('COQ-ECHARPE', '', 22, 0),
  ('COQ-GILET', '', 0, 1),
  ('COQ-GOURDE', '', 45, 0),
  ('COQ-HOODIE', 'S', 0, 1),
  ('COQ-HOODIE', 'M', 6, 2),
  ('COQ-HOODIE', 'L', 6, 3),
  ('COQ-HOODIE', 'XL', 2, 4),
  ('COQ-MANCHES', 'S', 6, 1),
  ('COQ-MANCHES', 'M', 11, 2),
  ('COQ-MANCHES', 'L', 9, 3),
  ('COQ-MANCHES', 'XL', 5, 4),
  ('COQ-MARQUEPAGE', '', 0, 0),
  ('COQ-MUG', '', 54, 0),
  ('COQ-PLAID', '', 14, 0),
  ('COQ-PORTECLES', '', 200, 0),
  ('COQ-POSTER', '', 35, 0),
  ('COQ-REBOOTS', '38', 7, 1),
  ('COQ-REBOOTS', '40', 9, 2),
  ('COQ-REBOOTS', '42', 10, 3),
  ('COQ-REBOOTS', '44', 5, 4),
  ('COQ-SOCKET', '36-39', 22, 1),
  ('COQ-SOCKET', '40-43', 20, 2),
  ('COQ-SOCKET', '44-46', 12, 3),
  ('COQ-STICKERS', '', 247, 0),
  ('COQ-THEIERE', '', 18, 0),
  ('COQ-TOTE', '', 120, 0),
  ('COQ-TSHIRT', 'S', 9, 1),
  ('COQ-TSHIRT', 'M', 14, 2),
  ('COQ-TSHIRT', 'L', 11, 3),
  ('COQ-TSHIRT', 'XL', 4, 4);
